// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/add-product": {
    params: {};
  };
  "/edit-product/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/add-product" | "/edit-product/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/products.tsx": {
    id: "routes/products";
    page: "/products";
  };
  "routes/add-product.tsx": {
    id: "routes/add-product";
    page: "/add-product";
  };
  "routes/edit-product.tsx": {
    id: "routes/edit-product";
    page: "/edit-product/:id";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/products": typeof import("./app/routes/products.tsx");
  "routes/add-product": typeof import("./app/routes/add-product.tsx");
  "routes/edit-product": typeof import("./app/routes/edit-product.tsx");
};